In [1]:
# 1. Viết chương trình NumPy để chuyển đổi một danh sách các giá trị số thành mảng NumPy một chiều.
# 2. Viết chương trình NumPy để tạo ma trận 3x3 với các giá trị từ 2 đến 10.
# 3. Viết chương trình NumPy để đảo ngược một mảng (phần tử đầu tiên trở thành cuối cùng).
# 4. Viết chương trình NumPy để chuyển đổi mảng sang kiểu `float`.
# 5. Viết chương trình NumPy để tạo mảng 2D có giá trị `1` ở viền và `0` ở bên trong.
# 6. Viết chương trình NumPy để tạo ma trận 8x8 và điền theo mẫu bàn cờ (checkerboard).
# 7. Viết chương trình NumPy để chuyển đổi giá trị nhiệt độ từ độ C sang độ F. (Công thức: `F = C * 9/5 + 32`)
# 8. Viết chương trình NumPy để lấy chỉ số (index) của các phần tử đã được sắp xếp trong mảng.

In [2]:
import numpy as np

In [3]:
# 1. Viết chương trình NumPy để chuyển đổi một danh sách các giá trị số thành mảng NumPy một chiều.

In [4]:
lst = [1, 2, 3, 4, 5]
arr = np.array(lst)

In [5]:
print("Mảng NumPy 1 chiều:", arr)

Mảng NumPy 1 chiều: [1 2 3 4 5]


In [6]:
# 2. Viết chương trình NumPy để tạo ma trận 3x3 với các giá trị từ 2 đến 10.

In [7]:
matrix = np.arange(2, 11).reshape(3, 3)

In [8]:
print("Ma trận 3x3 từ 2 đến 10:\n", matrix)

Ma trận 3x3 từ 2 đến 10:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [9]:
# 3. Viết chương trình NumPy để đảo ngược một mảng (phần tử đầu tiên trở thành cuối cùng).

In [10]:
arr = np.array([10, 20, 30, 40, 50])

In [11]:
print("Mảng ban đầu:", arr)

Mảng ban đầu: [10 20 30 40 50]


In [12]:
reversed_arr = arr[::-1]

In [13]:
print("Mảng sau khi đảo ngược:", reversed_arr)

Mảng sau khi đảo ngược: [50 40 30 20 10]


In [14]:
# 4. Viết chương trình NumPy để chuyển đổi mảng sang kiểu `float`.

In [15]:
arr = np.array([1, 2, 3, 4])

In [16]:
print("Mảng ban đầu:", arr, arr.dtype)

Mảng ban đầu: [1 2 3 4] int64


In [17]:
float_arr = arr.astype(float)

In [18]:
print("Mảng float:", float_arr, float_arr.dtype)

Mảng float: [1. 2. 3. 4.] float64


In [19]:
float_arr = arr.astype(np.float16)

In [20]:
print("Mảng float:", float_arr, float_arr.dtype)

Mảng float: [1. 2. 3. 4.] float16


In [21]:
# 5. Viết chương trình NumPy để tạo mảng 2D có giá trị `1` ở viền và `0` ở bên trong.

In [22]:
arr = np.ones((5, 5), dtype=int)

In [23]:
print("Mảng 2D ban đầu:\n", arr)

Mảng 2D ban đầu:
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [24]:
arr[1:-1, 1:-1] = 0

In [25]:
print("Mảng 2D với viền là 1 và bên trong là 0:\n", arr)

Mảng 2D với viền là 1 và bên trong là 0:
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [26]:
# 6. Viết chương trình NumPy để tạo ma trận 8x8 và điền theo mẫu bàn cờ (checkerboard).

In [27]:
arr = np.zeros((8, 8), dtype=int)

In [28]:
print("Mảng 2D ban đầu:\n", arr)

Mảng 2D ban đầu:
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [29]:
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1

In [30]:
print("Mẫu bàn cờ 8x8:\n", arr)

Mẫu bàn cờ 8x8:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [31]:
# 7. Viết chương trình NumPy để chuyển đổi giá trị nhiệt độ từ độ C sang độ F. (Công thức: `F = C * 9 / 5 + 32`)

In [32]:
celsius = np.array([0, 20, 37, 100])

In [33]:
print("Độ C:", celsius)

Độ C: [  0  20  37 100]


In [34]:
fahrenheit = celsius * 9 / 5 + 32

In [35]:
print("Độ F:", fahrenheit)

Độ F: [ 32.   68.   98.6 212. ]


In [36]:
# 8. Viết chương trình NumPy để lấy chỉ số (index) của các phần tử đã được sắp xếp trong mảng.

In [37]:
arr = np.array([40, 10, 30, 20])

In [38]:
print("Mảng ban đầu:", arr)

Mảng ban đầu: [40 10 30 20]


In [39]:
sorted_indices = np.argsort(arr)

In [40]:
print("Chỉ số sau khi sắp xếp:", sorted_indices)

Chỉ số sau khi sắp xếp: [1 3 2 0]
