In [1]:
import torch

# 1. Khởi tạo Tensor
## 1.1. torch.tensor()

In [2]:
x = [[1, 2],[3, 4]]
x

[[1, 2], [3, 4]]

In [3]:
type(x)

list

In [4]:
# Tạo Tensor từ List
x = torch.tensor(x)
x

/var/folders/8_/m50_8s_942q571m12vh47_q80000gq/T/ipykernel_80271/2714855990.py:2: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  x = torch.tensor(x)


tensor([[1, 2],
        [3, 4]])

In [5]:
x.shape

torch.Size([2, 2])

## 1.2. torch.zeros()

In [6]:
x_0 = torch.zeros((2, 3))
x_0

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
x_0.shape

torch.Size([2, 3])

## 1.3. torch.ones()

In [8]:
x_1 = torch.ones((2, 3))
x_1

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
x_1.shape

torch.Size([2, 3])

## 1.4. torch.eye()

In [10]:
x = torch.eye(4)
x

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [11]:
x.shape

torch.Size([4, 4])

## 1.5. torch.arange()

In [12]:
x = torch.arange(2, 10, 1)
x

tensor([2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x.shape

torch.Size([8])

## 1.6. torch.linspace()

In [14]:
x = torch.linspace(2, 10, 20)
x

tensor([ 2.0000,  2.4211,  2.8421,  3.2632,  3.6842,  4.1053,  4.5263,  4.9474,
         5.3684,  5.7895,  6.2105,  6.6316,  7.0526,  7.4737,  7.8947,  8.3158,
         8.7368,  9.1579,  9.5789, 10.0000])

In [15]:
x.shape

torch.Size([20])

## 1.7. torch.rand()

In [16]:
x = torch.rand(4, 3)
x

tensor([[0.4707, 0.3870, 0.3741],
        [0.5894, 0.1751, 0.0040],
        [0.5602, 0.5460, 0.6198],
        [0.5459, 0.7228, 0.8083]])

In [17]:
x.shape

torch.Size([4, 3])

## 1.7. torch.randn()

In [18]:
x = torch.randn(4, 3)
x

tensor([[ 0.2234,  1.6994,  0.8893],
        [-0.3684, -1.3858, -0.1882],
        [ 1.0580,  0.8402, -0.0978],
        [-0.2036, -2.0304,  0.5946]])

In [19]:
x.shape

torch.Size([4, 3])

## 1.9. torch.ones_like()

In [20]:
x

tensor([[ 0.2234,  1.6994,  0.8893],
        [-0.3684, -1.3858, -0.1882],
        [ 1.0580,  0.8402, -0.0978],
        [-0.2036, -2.0304,  0.5946]])

In [21]:
y_1 = torch.ones_like(x)
y_1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [22]:
y_1.shape

torch.Size([4, 3])

## 1.10. torch.rand_like()

In [23]:
x

tensor([[ 0.2234,  1.6994,  0.8893],
        [-0.3684, -1.3858, -0.1882],
        [ 1.0580,  0.8402, -0.0978],
        [-0.2036, -2.0304,  0.5946]])

In [24]:
y = torch.rand_like(x)
y

tensor([[0.4034, 0.7114, 0.0346],
        [0.6697, 0.2785, 0.4705],
        [0.6966, 0.5684, 0.6690],
        [0.6068, 0.3624, 0.4912]])

In [25]:
y.shape

torch.Size([4, 3])

# 2. Tính toán với tensor

In [26]:
x = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [27]:
x.shape

torch.Size([3, 4])

In [28]:
y = torch.tensor([[19, 28, 37, 46], [55, 64, 73, 82], [91, 100, 119, 128]])
y

tensor([[ 19,  28,  37,  46],
        [ 55,  64,  73,  82],
        [ 91, 100, 119, 128]])

In [29]:
y.shape

torch.Size([3, 4])

## 2.1. torch.t()

In [30]:
x

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [31]:
x.T

tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])

In [32]:
x.T.T

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

## 2.2. torch.add()

In [33]:
z = torch.add(x, y)
z

tensor([[ 20,  30,  40,  50],
        [ 60,  70,  80,  90],
        [100, 110, 130, 140]])

In [34]:
z.shape

torch.Size([3, 4])

## 2.3. torch.sub()

In [35]:
z = torch.sub(x, y)
z

tensor([[ -18,  -26,  -34,  -42],
        [ -50,  -58,  -66,  -74],
        [ -82,  -90, -108, -116]])

In [36]:
z.shape

torch.Size([3, 4])

## 2.4. torch.mul()

In [37]:
z = torch.mul(x, y)
z

tensor([[  19,   56,  111,  184],
        [ 275,  384,  511,  656],
        [ 819, 1000, 1309, 1536]])

In [38]:
z.shape

torch.Size([3, 4])

## 2.5. torch.div()   

In [39]:
z = torch.div(x, y)
z

tensor([[0.0526, 0.0714, 0.0811, 0.0870],
        [0.0909, 0.0938, 0.0959, 0.0976],
        [0.0989, 0.1000, 0.0924, 0.0938]])

In [40]:
z.shape

torch.Size([3, 4])

## 2.6. torch.mm()

In [41]:
z = torch.mm(x, y)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 3x4)

In [42]:
x.shape

torch.Size([3, 4])

In [43]:
y.shape

torch.Size([3, 4])

In [44]:
y.T.shape

torch.Size([4, 3])

In [45]:
z = torch.mm(x, y.T)
z

tensor([[ 370,  730, 1160],
        [ 890, 1826, 2912],
        [1410, 2922, 4664]])

In [46]:
z.shape

torch.Size([3, 3])

## 2.7. torch.matmul()

In [47]:
z = torch.matmul(x, y.T)
z

tensor([[ 370,  730, 1160],
        [ 890, 1826, 2912],
        [1410, 2922, 4664]])

In [48]:
z.shape

torch.Size([3, 3])

In [49]:
x

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [50]:
y.T

tensor([[ 19,  55,  91],
        [ 28,  64, 100],
        [ 37,  73, 119],
        [ 46,  82, 128]])

In [51]:
y.T.shape

torch.Size([4, 3])

In [52]:
y_hat = torch.tensor([19, 28, 37, 46])
y_hat

tensor([19, 28, 37, 46])

In [53]:
y_hat.shape

torch.Size([4])

In [54]:
z = torch.matmul(x, y_hat)
z

tensor([ 370,  890, 1410])

## 2.8. torch.sum()

In [55]:
z = torch.sum(x)
z

tensor(78)

## 2.9. torch.mean()

In [56]:
z = torch.mean(x)
z

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [57]:
z = torch.mean(x.float())
z

tensor(6.5000)

## 2.10. torch.max()

In [58]:
z = torch.max(x)
z

tensor(12)

## 2.11. torch.min()

In [59]:
z = torch.min(x)
z

tensor(1)

## 2.12. torch.exp()

In [60]:
z = torch.exp(x)
z

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03],
        [8.1031e+03, 2.2026e+04, 5.9874e+04, 1.6275e+05]])

## 2.13. torch.log()

In [61]:
z = torch.log(x)
z

tensor([[0.0000, 0.6931, 1.0986, 1.3863],
        [1.6094, 1.7918, 1.9459, 2.0794],
        [2.1972, 2.3026, 2.3979, 2.4849]])

## 2.14. torch.sin(), torch.cos(), torch.tan()

In [62]:
z = torch.sin(x)
z

tensor([[ 0.8415,  0.9093,  0.1411, -0.7568],
        [-0.9589, -0.2794,  0.6570,  0.9894],
        [ 0.4121, -0.5440, -1.0000, -0.5366]])

In [63]:
z = torch.cos(x)
z

tensor([[ 0.5403, -0.4161, -0.9900, -0.6536],
        [ 0.2837,  0.9602,  0.7539, -0.1455],
        [-0.9111, -0.8391,  0.0044,  0.8439]])

In [64]:
z = torch.tan(x)
z

tensor([[ 1.5574e+00, -2.1850e+00, -1.4255e-01,  1.1578e+00],
        [-3.3805e+00, -2.9101e-01,  8.7145e-01, -6.7997e+00],
        [-4.5232e-01,  6.4836e-01, -2.2595e+02, -6.3586e-01]])

## 2.15. torch.sqrt()

In [65]:
z = torch.sqrt(x)
z

tensor([[1.0000, 1.4142, 1.7321, 2.0000],
        [2.2361, 2.4495, 2.6458, 2.8284],
        [3.0000, 3.1623, 3.3166, 3.4641]])

# 3. Index và Slicing

In [66]:
x

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [67]:
x[1]

tensor([5, 6, 7, 8])

In [68]:
x[1, 2]

tensor(7)

In [69]:
x

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [70]:
x[0, 1:3]

tensor([2, 3])

In [71]:
x[1, 1:3]

tensor([6, 7])

# 4. Thay đổi hình dạng tensor

## 4.1. tensor.view()

In [72]:
x

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [73]:
x_new = x.view(2, 6)
x_new

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

## 4.2. tensor.reshape()

In [74]:
x

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [75]:
x_new = x.reshape(2, 6)
x_new

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

## 4.3. tensor.transpose()

In [76]:
x

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [77]:
x.shape

torch.Size([3, 4])

In [78]:
x_trans = x.transpose(0, 1)
x_trans

tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])

In [79]:
x_trans.shape

torch.Size([4, 3])

In [80]:
x_trans = x.transpose(1, 0)
x_trans

tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])

# 5. Nối tensor

In [81]:
x

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [82]:
y

tensor([[ 19,  28,  37,  46],
        [ 55,  64,  73,  82],
        [ 91, 100, 119, 128]])

In [83]:
z = torch.cat((x, y), axis=0)
z

tensor([[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12],
        [ 19,  28,  37,  46],
        [ 55,  64,  73,  82],
        [ 91, 100, 119, 128]])

In [84]:
z = torch.cat((x, y), axis=1)
z

tensor([[  1,   2,   3,   4,  19,  28,  37,  46],
        [  5,   6,   7,   8,  55,  64,  73,  82],
        [  9,  10,  11,  12,  91, 100, 119, 128]])

# 6. Chuyển tensor giữa CPU và GPU (CUDA)

In [85]:
x.cuda()

AssertionError: Torch not compiled with CUDA enabled

In [86]:
x.to(device='cuda')

AssertionError: Torch not compiled with CUDA enabled

In [87]:
x.cpu()

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [88]:
x.to(device='cpu')

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])